# Config file for automatic testing at travis-ci.com

language: python
dist: xenial
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - black --check .
  - flake8 imgwrench tests
  - python -m unittest discover -v
