'''base64 encoded image data for testing'''

import base64
import io

from PIL import Image

pixel1x1 = base64.b64decode('''
/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAIVcZHVkU4V1bHWW
joWeyP/ZyLe3yP////L/////////////////////////////////////////////////////2wBD
AY6WlsivyP/Z2f//////////////////////////////////////////////////////////////
////////////wgARCAABAAEDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAA//EABQBAQAA
AAAAAAAAAAAAAAAAAAD/2gAMAwEAAhADEAAAAUP/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEB
AAEFAn//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAA
AAAA/9oACAECAQE/AX//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/An//xAAUEAEAAAAA
AAAAAAAAAAAAAAAA/9oACAEBAAE/IX//2gAMAwEAAgADAAAAEB//xAAUEQEAAAAAAAAAAAAAAAAA
AAAA/9oACAEDAQE/EH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EH//xAAUEAEAAAAA
AAAAAAAAAAAAAAAA/9oACAEBAAE/EH//2Q==''')

with io.BytesIO(pixel1x1) as f:
    pixel1x1_img = Image.open(f)
    pixel1x1_img.load()

png1x1 = base64.b64decode('''
iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI
WXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wISEAcwqWoK4wAAAAh0RVh0Q29tbWVudAD2zJa/AAAA
DUlEQVQI12NgYGBgAAAABQABXvMqOgAAAABJRU5ErkJggg==''')

with io.BytesIO(png1x1) as f:
    png1x1_img = Image.open(f)
    png1x1_img.load()

white100x100 = base64.b64decode('''
/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAKBueIx4ZKCMgoy0
qqC+8P//8Nzc8P//////////////////////////////////////////////////////////2wBD
Aaq0tPDS8P//////////////////////////////////////////////////////////////////
////////////wgARCABkAGQDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAUAQEA
AAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8QAFBABAAAAAAAAAAAAAAAAAAAA
cP/aAAgBAQABBQIp/8QAFBEBAAAAAAAAAAAAAAAAAAAAcP/aAAgBAwEBPwEp/8QAFBEBAAAAAAAA
AAAAAAAAAAAAcP/aAAgBAgEBPwEp/8QAFBABAAAAAAAAAAAAAAAAAAAAcP/aAAgBAQAGPwIp/8QA
FBABAAAAAAAAAAAAAAAAAAAAcP/aAAgBAQABPyEp/9oADAMBAAIAAwAAABAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8QAFBEB
AAAAAAAAAAAAAAAAAAAAcP/aAAgBAwEBPxAp/8QAFBEBAAAAAAAAAAAAAAAAAAAAcP/aAAgBAgEB
PxAp/8QAFBABAAAAAAAAAAAAAAAAAAAAcP/aAAgBAQABPxAp/9k=''')

with io.BytesIO(white100x100) as f:
    white100x100_img = Image.open(f)
    white100x100_img.load()

white117x100 = base64.b64decode('''
/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAKBueIx4ZKCMgoy0
qqC+8P//8Nzc8P//////////////////////////////////////////////////////////2wBD
Aaq0tPDS8P//////////////////////////////////////////////////////////////////
////////////wgARCABkAHUDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAUAQEA
AAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//EABQQAQAAAAAA
AAAAAAAAAAAAAHD/2gAIAQEAAQUCQ//EABQRAQAAAAAAAAAAAAAAAAAAAHD/2gAIAQMBAT8BQ//E
ABQRAQAAAAAAAAAAAAAAAAAAAHD/2gAIAQIBAT8BQ//EABQQAQAAAAAAAAAAAAAAAAAAAHD/2gAI
AQEABj8CQ//EABQQAQAAAAAAAAAAAAAAAAAAAHD/2gAIAQEAAT8hQ//aAAwDAQACAAMAAAAQAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAH//xAAUEQEAAAAAAAAAAAAAAAAAAABw/9oACAEDAQE/EEP/xAAUEQEAAAAA
AAAAAAAAAAAAAABw/9oACAECAQE/EEP/xAAUEAEAAAAAAAAAAAAAAAAAAABw/9oACAEBAAE/EEP/
2Q==''')

with io.BytesIO(white117x100) as f:
    white117x100_img = Image.open(f)
    white117x100_img.load()

white100x123 = base64.b64decode('''
/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAKBueIx4ZKCMgoy0
qqC+8P//8Nzc8P//////////////////////////////////////////////////////////2wBD
Aaq0tPDS8P//////////////////////////////////////////////////////////////////
////////////wgARCAB7AGQDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAUAQEA
AAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8QAFBAB
AAAAAAAAAAAAAAAAAAAAcP/aAAgBAQABBQJQ/8QAFBEBAAAAAAAAAAAAAAAAAAAAcP/aAAgBAwEB
PwFQ/8QAFBEBAAAAAAAAAAAAAAAAAAAAcP/aAAgBAgEBPwFQ/8QAFBABAAAAAAAAAAAAAAAAAAAA
cP/aAAgBAQAGPwJQ/8QAFBABAAAAAAAAAAAAAAAAAAAAcP/aAAgBAQABPyFQ/9oADAMBAAIAAwAA
ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAABw/9oACAEDAQE/EFD/
xAAUEQEAAAAAAAAAAAAAAAAAAABw/9oACAECAQE/EFD/xAAUEAEAAAAAAAAAAAAAAAAAAABw/9oA
CAEBAAE/EFD/2Q==''')

with io.BytesIO(white100x123) as f:
    white100x123_img = Image.open(f)
    white100x123_img.load()

white150x100 = base64.b64decode('''
/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAKBueIx4ZKCMgoy0
qqC+8P//8Nzc8P//////////////////////////////////////////////////////////2wBD
Aaq0tPDS8P//////////////////////////////////////////////////////////////////
////////////wgARCABkAJYDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAUAQEA
AAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD/xAAUEAEAAAAAAAAAAAAAAAAAAABw/9oACAEBAAEFAnf/xAAUEQEAAAAAAAAAAAAA
AAAAAABw/9oACAEDAQE/AXf/xAAUEQEAAAAAAAAAAAAAAAAAAABw/9oACAECAQE/AXf/xAAUEAEA
AAAAAAAAAAAAAAAAAABw/9oACAEBAAY/Anf/xAAUEAEAAAAAAAAAAAAAAAAAAABw/9oACAEBAAE/
IXf/2gAMAwEAAgADAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//EABQR
AQAAAAAAAAAAAAAAAAAAAHD/2gAIAQMBAT8Qd//EABQRAQAAAAAAAAAAAAAAAAAAAHD/2gAIAQIB
AT8Qd//EABQQAQAAAAAAAAAAAAAAAAAAAHD/2gAIAQEAAT8Qd//Z''')

with io.BytesIO(white150x100) as f:
    white150x100_img = Image.open(f)
    white150x100_img.load()
