'''base64 encoded image data for testing'''

import base64
import io

from PIL import Image

pixel1x1 = base64.b64decode('''
/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAIVcZHVkU4V1bHWW
joWeyP/ZyLe3yP////L/////////////////////////////////////////////////////2wBD
AY6WlsivyP/Z2f//////////////////////////////////////////////////////////////
////////////wgARCAABAAEDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAA//EABQBAQAA
AAAAAAAAAAAAAAAAAAD/2gAMAwEAAhADEAAAAUP/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEB
AAEFAn//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAA
AAAA/9oACAECAQE/AX//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/An//xAAUEAEAAAAA
AAAAAAAAAAAAAAAA/9oACAEBAAE/IX//2gAMAwEAAgADAAAAEB//xAAUEQEAAAAAAAAAAAAAAAAA
AAAA/9oACAEDAQE/EH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EH//xAAUEAEAAAAA
AAAAAAAAAAAAAAAA/9oACAEBAAE/EH//2Q==''')

with io.BytesIO(pixel1x1) as f:
    pixel1x1_img = Image.open(f)
    pixel1x1_img.load()
